/* Nexus Research: catalog of lab chemicals and supplies.
   RESEARCH USE ONLY. Not for human or veterinary use.

   Every entry carries the identity and handling data a lab actually
   needs to work with the material: CAS, formula, molecular weight,
   purity and the method used to determine it, form, and storage.
   `lot` is the batch whose test report is on file.
   `box` is the price for a box of 10 units, quoted on the wholesale desk.

   CAS numbers appear only where verified. Coded analogue names and
   multi-peptide blends carry none, by design.
*/
const PRODUCTS = [
  {
    id: "bpc-157",
    name: "BPC-157",
    subtitle: "Body protection compound 157",
    category: "peptides",
    cas: "137525-51-0",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2602-A",
    tagline: "Pentadecapeptide reference compound.",
    description: "A synthetic 15-amino-acid peptide used as a reference compound in in-vitro laboratory study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "In-vitro assay controls"],
    price: 44.1,
    box: 392,
    img: "nexus-vial"
  },
  {
    id: "tb-500",
    name: "TB-500",
    subtitle: "Thymosin beta-4 fragment",
    category: "peptides",
    cas: "77591-33-4",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2602-B",
    tagline: "Actin-binding peptide fragment.",
    description: "A synthetic fragment corresponding to a region of thymosin beta-4, supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Cytoskeletal chemistry"],
    price: 63,
    box: 560,
    img: "nexus-vial"
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    subtitle: "Copper peptide, glycyl-L-histidyl-L-lysine",
    category: "peptides",
    cas: "89030-95-5",
    formula: "C14H22CuN6O4",
    mw: "403.91 g/mol",
    sequence: "Gly-His-Lys · Cu(II)",
    size: "50 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2601-A",
    tagline: "Copper-binding tripeptide reference compound for in-vitro study.",
    description: "The copper(II) complex of the tripeptide glycyl-L-histidyl-L-lysine, used as a reference compound in in-vitro extracellular matrix and metalloprotein studies. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Extracellular matrix studies", "Cell culture models", "Metalloprotein chemistry"],
    price: 45,
    box: 400,
    img: "nexus-vial"
  },
  {
    id: "ghk",
    name: "GHK Tripeptide",
    subtitle: "Glycyl-L-histidyl-L-lysine",
    category: "peptides",
    cas: "49557-75-7",
    formula: "C14H24N6O4",
    mw: "340.38 g/mol",
    sequence: "Gly-His-Lys",
    size: "50 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2601-B",
    tagline: "The uncomplexed tripeptide, for use as a copper-free control.",
    description: "The free tripeptide corresponding to the copper complex GHK-Cu. Commonly run as a copper-free control alongside GHK-Cu to separate peptide effects from metal effects. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Control for GHK-Cu experiments", "Peptide reference standard", "Chelation studies"],
    price: 39,
    box: 347,
    img: "nexus-vial"
  },
  {
    id: "epithalon",
    name: "Epithalon",
    subtitle: "Ala-Glu-Asp-Gly tetrapeptide",
    category: "peptides",
    cas: "307297-39-8",
    formula: null,
    mw: null,
    sequence: "Ala-Glu-Asp-Gly",
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2603-A",
    tagline: "Synthetic tetrapeptide reference compound.",
    description: "A synthetic tetrapeptide supplied as a reference compound for in-vitro laboratory study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "In-vitro assay controls"],
    price: 49.5,
    box: 440,
    img: "nexus-vial"
  },
  {
    id: "selank",
    name: "Selank",
    subtitle: "Heptapeptide",
    category: "peptides",
    cas: "129954-34-3",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2603-B",
    tagline: "Synthetic heptapeptide reference compound.",
    description: "A synthetic heptapeptide supplied as a reference compound for in-vitro laboratory study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Analytical method development"],
    price: 36,
    box: 320,
    img: "nexus-vial"
  },
  {
    id: "semax",
    name: "Semax",
    subtitle: "Heptapeptide",
    category: "peptides",
    cas: "80714-27-0",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2603-C",
    tagline: "Synthetic heptapeptide reference compound.",
    description: "A synthetic heptapeptide supplied as a reference compound for in-vitro laboratory study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Analytical method development"],
    price: 38.25,
    box: 340,
    img: "nexus-vial"
  },
  {
    id: "semax-selank",
    name: "Semax and Selank Blend",
    subtitle: "Two-peptide blend",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2603-D",
    tagline: "Blended reference material, both peptides in one vial.",
    description: "A blended preparation containing both heptapeptides in a single vial, supplied as reference material for in-vitro laboratory study. Each component is confirmed separately by the testing laboratory. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Blended reference material", "Method development"],
    price: 94.5,
    box: 840,
    img: "nexus-vial"
  },
  {
    id: "dsip",
    name: "DSIP",
    subtitle: "Delta sleep-inducing peptide",
    category: "peptides",
    cas: "62568-57-4",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2604-A",
    tagline: "Nonapeptide reference compound.",
    description: "A synthetic nonapeptide supplied as a reference compound for in-vitro laboratory study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "In-vitro assay controls"],
    price: 45,
    box: 400,
    img: "nexus-vial"
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    subtitle: "Pentapeptide",
    category: "peptides",
    cas: "170851-70-4",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-A",
    tagline: "Synthetic pentapeptide reference compound.",
    description: "A synthetic pentapeptide supplied as a reference compound for in-vitro receptor and analytical study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 81,
    box: 720,
    img: "nexus-vial"
  },
  {
    id: "cjc-1295-no-dac",
    name: "CJC-1295 no DAC",
    subtitle: "Modified GRF (1-29)",
    category: "peptides",
    cas: "863288-34-0",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-B",
    tagline: "Modified growth hormone releasing factor fragment.",
    description: "A modified 29-amino-acid releasing-factor fragment without the drug affinity complex, supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 49.5,
    box: 440,
    img: "nexus-vial"
  },
  {
    id: "cjc-1295-dac",
    name: "CJC-1295 with DAC",
    subtitle: "With drug affinity complex",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-C",
    tagline: "Releasing-factor analogue with the affinity complex.",
    description: "A releasing-factor analogue carrying the drug affinity complex, supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 72,
    box: 640,
    img: "nexus-vial"
  },
  {
    id: "cjc-ipamorelin",
    name: "CJC-1295 no DAC and Ipamorelin",
    subtitle: "5 mg + 5 mg blend",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-D",
    tagline: "Two-peptide blend, 5 mg of each.",
    description: "A blended preparation containing 5 mg of each peptide in a single vial, supplied as reference material for in-vitro study. Each component is confirmed separately by the testing laboratory. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Blended reference material", "Receptor binding studies"],
    price: 80.1,
    box: 712,
    img: "nexus-vial"
  },
  {
    id: "sermorelin",
    name: "Sermorelin",
    subtitle: "GRF (1-29) amide",
    category: "peptides",
    cas: "86168-78-7",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-E",
    tagline: "29-amino-acid releasing-factor fragment.",
    description: "A synthetic 29-amino-acid releasing-factor fragment supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 45,
    box: 400,
    img: "nexus-vial"
  },
  {
    id: "tesamorelin",
    name: "Tesamorelin",
    subtitle: "Trans-3-hexenoyl GRF (1-44)",
    category: "peptides",
    cas: "218949-48-5",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-F",
    tagline: "44-amino-acid releasing-factor analogue.",
    description: "A synthetic releasing-factor analogue supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 85.5,
    box: 760,
    img: "nexus-vial"
  },
  {
    id: "tesamorelin-ipamorelin",
    name: "Tesamorelin and Ipamorelin",
    subtitle: "8 mg + 2 mg blend",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2605-G",
    tagline: "Two-peptide blend, 8 mg and 2 mg.",
    description: "A blended preparation containing both peptides in a single vial at an 8 mg to 2 mg ratio, supplied as reference material for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Blended reference material", "Receptor binding studies"],
    price: 103.5,
    box: 920,
    img: "nexus-vial"
  },
  {
    id: "mots-c",
    name: "MOTS-c",
    subtitle: "Mitochondrial-derived peptide",
    category: "peptides",
    cas: "1627580-64-6",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2606-A",
    tagline: "16-amino-acid mitochondrial-derived peptide.",
    description: "A synthetic 16-amino-acid mitochondrial-derived peptide supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Mitochondrial biochemistry"],
    price: 67.5,
    box: 600,
    img: "nexus-vial"
  },
  {
    id: "kisspeptin",
    name: "Kisspeptin-10",
    subtitle: "Metastin fragment 45-54",
    category: "peptides",
    cas: "374675-21-5",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2606-B",
    tagline: "Decapeptide reference compound.",
    description: "A synthetic decapeptide corresponding to a metastin fragment, supplied as a reference compound for in-vitro receptor study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 67.5,
    box: 600,
    img: "nexus-vial"
  },
  {
    id: "aod-9604",
    name: "AOD-9604",
    subtitle: "hGH fragment 176-191",
    category: "peptides",
    cas: "221231-10-3",
    formula: null,
    mw: null,
    sequence: null,
    size: "5 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2606-C",
    tagline: "Growth hormone fragment reference compound.",
    description: "A synthetic peptide corresponding to a C-terminal fragment of human growth hormone, supplied as a reference compound for in-vitro study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "In-vitro assay controls"],
    price: 63,
    box: 560,
    img: "nexus-vial"
  },
  {
    id: "igf1-lr3",
    name: "IGF-1 LR3",
    subtitle: "Long R3 insulin-like growth factor 1",
    category: "peptides",
    cas: "946870-92-4",
    formula: null,
    mw: null,
    sequence: null,
    size: "1 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2606-D",
    tagline: "83-amino-acid analogue reference protein.",
    description: "An 83-amino-acid analogue supplied as a reference protein for in-vitro cell culture study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Cell culture reference protein", "Receptor binding studies"],
    price: 94.5,
    box: 840,
    img: "nexus-vial"
  },
  {
    id: "mt-2",
    name: "MT-2",
    subtitle: "Melanotan II",
    category: "peptides",
    cas: "121062-08-6",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2607-A",
    tagline: "Cyclic heptapeptide analogue.",
    description: "A synthetic cyclic heptapeptide analogue supplied as a reference compound for in-vitro receptor study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 58.5,
    box: 520,
    img: "nexus-vial"
  },
  {
    id: "hcg",
    name: "HCG",
    subtitle: "Human chorionic gonadotropin",
    category: "peptides",
    cas: "9002-61-3",
    formula: null,
    mw: null,
    sequence: null,
    size: "5000 IU",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2607-B",
    tagline: "Glycoprotein hormone reference standard.",
    description: "A glycoprotein supplied as a reference standard for in-vitro immunoassay and analytical work. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Immunoassay reference standard", "Analytical method development"],
    price: 67.5,
    box: 600,
    img: "nexus-vial"
  },
  {
    id: "cagrilintide",
    name: "Cagrilintide",
    subtitle: "Amylin analogue",
    category: "peptides",
    cas: "1415456-99-3",
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2608-A",
    tagline: "Long-acting amylin analogue reference compound.",
    description: "A synthetic amylin analogue supplied as a reference compound for in-vitro receptor study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "Receptor binding studies"],
    price: 99,
    box: 880,
    img: "nexus-vial"
  },
  {
    id: "glp1-sm",
    name: "GLP1-SM",
    subtitle: "GLP-1 receptor reference analogue",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2608-B",
    tagline: "GLP-1 receptor reference analogue.",
    description: "A synthetic analogue supplied as a reference compound for in-vitro GLP-1 receptor study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Receptor binding studies", "Analytical method development"],
    price: 72,
    box: 640,
    img: "nexus-vial"
  },
  {
    id: "glp2-tz",
    name: "GLP2-TZ",
    subtitle: "Dual receptor reference analogue",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2608-C",
    tagline: "Dual receptor reference analogue.",
    description: "A synthetic analogue supplied as a reference compound for in-vitro receptor study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Receptor binding studies", "Analytical method development"],
    price: 81,
    box: 720,
    img: "nexus-vial"
  },
  {
    id: "glp3-rt",
    name: "GLP3-RT",
    subtitle: "Triple receptor reference analogue",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2608-D",
    tagline: "Triple receptor reference analogue.",
    description: "A synthetic analogue supplied as a reference compound for in-vitro receptor study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Receptor binding studies", "Analytical method development"],
    price: 94.5,
    box: 840,
    img: "nexus-vial"
  },
  {
    id: "nad-plus",
    name: "NAD+",
    subtitle: "Nicotinamide adenine dinucleotide",
    category: "biochemicals",
    cas: "53-84-9",
    formula: "C21H27N7O14P2",
    mw: "663.43 g/mol",
    sequence: null,
    size: "500 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2609-A",
    tagline: "Redox cofactor reference reagent.",
    description: "The oxidised form of nicotinamide adenine dinucleotide, a standard cofactor reagent in enzymology and redox chemistry. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Enzyme assay cofactor", "Redox chemistry", "Analytical reference"],
    price: 76.5,
    box: 680,
    img: "nexus-vial"
  },
  {
    id: "kpv",
    name: "KPV",
    subtitle: "Lys-Pro-Val tripeptide",
    category: "peptides",
    cas: "63968-82-1",
    formula: null,
    mw: null,
    sequence: "Lys-Pro-Val",
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2609-B",
    tagline: "Tripeptide reference compound.",
    description: "A synthetic tripeptide supplied as a reference compound for in-vitro laboratory study. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Peptide reference standard", "In-vitro assay controls"],
    price: 42,
    box: 373,
    img: "nexus-vial"
  },
  {
    id: "glow",
    name: "GLOW",
    subtitle: "GHK-Cu, BPC-157 and TB-500 blend, 70 mg",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "70 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2610-A",
    tagline: "Three-peptide blend in a single vial.",
    description: "A blended preparation containing GHK-Cu, BPC-157 and TB-500 in a single vial, supplied as reference material for in-vitro study. Each component is confirmed separately by the testing laboratory. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Blended reference material", "Method development"],
    price: 112.5,
    box: 1000,
    img: "nexus-vial"
  },
  {
    id: "wolverine",
    name: "WOLVERINE",
    subtitle: "BPC-157 and TB-500 blend, 10 mg",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "10 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2610-B",
    tagline: "Two-peptide blend in a single vial.",
    description: "A blended preparation containing BPC-157 and TB-500 in a single vial, supplied as reference material for in-vitro study. Each component is confirmed separately by the testing laboratory. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Blended reference material", "Method development"],
    price: 76.5,
    box: 680,
    img: "nexus-vial"
  },
  {
    id: "klow",
    name: "KLOW",
    subtitle: "KPV, GHK-Cu, BPC-157 and TB-500 blend, 80 mg",
    category: "peptides",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "80 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a freezer at -20 °C, kept dry and out of the light. Ships at room temperature as a dry powder.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2610-C",
    tagline: "Four-peptide blend in a single vial.",
    description: "A blended preparation containing KPV, GHK-Cu, BPC-157 and TB-500 in a single vial, supplied as reference material for in-vitro study. Each component is confirmed separately by the testing laboratory. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Blended reference material", "Method development"],
    price: 108,
    box: 960,
    img: "nexus-vial"
  },
  {
    id: "glutathione-reduced",
    name: "L-Glutathione, Reduced",
    subtitle: "GSH",
    category: "biochemicals",
    cas: "70-18-8",
    formula: "C10H17N3O6S",
    mw: "307.32 g/mol",
    sequence: null,
    size: "1 g",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a fridge at 2 to 8 °C, kept dry.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2611-A",
    tagline: "Reference thiol compound for redox assays.",
    description: "Reduced glutathione is the principal intracellular thiol and a standard reference reagent in redox chemistry. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["GSH/GSSG ratio assays", "Redox buffer preparation", "Glutathione S-transferase substrate"],
    price: 34,
    box: 302,
    img: "nexus-vial"
  },
  {
    id: "glutathione-oxidized",
    name: "L-Glutathione, Oxidized",
    subtitle: "GSSG",
    category: "biochemicals",
    cas: "27025-41-8",
    formula: "C20H32N6O12S2",
    mw: "612.63 g/mol",
    sequence: null,
    size: "500 mg",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep in a fridge at 2 to 8 °C, dry and sealed from air.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2611-B",
    tagline: "Oxidised reference standard for redox work.",
    description: "The disulfide-linked dimer of GSH, used as the oxidised reference in redox determinations and calibration. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["GSH/GSSG standard curves", "Glutathione reductase assays", "Redox potential calibration"],
    price: 42,
    box: 373,
    img: "nexus-vial"
  },
  {
    id: "nac",
    name: "N-Acetyl-L-Cysteine",
    subtitle: "NAC",
    category: "biochemicals",
    cas: "616-91-1",
    formula: "C5H9NO3S",
    mw: "163.20 g/mol",
    sequence: null,
    size: "5 g",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Freeze-dried powder",
    storage: "Keep at room temperature, tightly sealed and dry.",
    solubility: "Dissolves in water and water-based buffers.",
    lot: "NR-2611-C",
    tagline: "Thiol reagent and reference standard.",
    description: "A thiol-bearing amino acid derivative used as a laboratory reagent and reference standard. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Thiol chemistry", "Analytical reference", "Buffer preparation"],
    price: 28,
    box: 249,
    img: "nexus-vial"
  },
  {
    id: "mk-677",
    name: "MK-677",
    subtitle: "Ibutamoren, capsule format",
    category: "capsules",
    cas: "159752-10-0",
    formula: null,
    mw: null,
    sequence: null,
    size: "60 capsules",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Capsules",
    storage: "Keep at room temperature, dry, in the original container.",
    solubility: null,
    lot: "NR-2612-A",
    tagline: "Reference compound supplied in capsule format.",
    description: "A synthetic reference compound supplied in capsule format for in-vitro laboratory study. Not for human or veterinary use. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Analytical reference", "Method development"],
    price: 103.5,
    box: 920,
    img: "nexus-vial"
  },
  {
    id: "rad-140",
    name: "RAD-140",
    subtitle: "Testolone, capsule format",
    category: "capsules",
    cas: "1182367-47-0",
    formula: null,
    mw: null,
    sequence: null,
    size: "60 capsules",
    purity: ">99%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Capsules",
    storage: "Keep at room temperature, dry, in the original container.",
    solubility: null,
    lot: "NR-2612-B",
    tagline: "Reference compound supplied in capsule format.",
    description: "A synthetic reference compound supplied in capsule format for in-vitro laboratory study. Not for human or veterinary use. Supplied as a sealed vial of freeze-dried powder. Each batch is tested by an outside laboratory for purity and identity, and the report is filed against the batch number printed on the vial. No preparation or usage guidance is supplied with this product.",
    apps: ["Analytical reference", "Method development"],
    price: 80.1,
    box: 712,
    img: "nexus-vial"
  },
  {
    id: "bacteriostatic-water",
    name: "Bacteriostatic Water",
    subtitle: "0.9% benzyl alcohol",
    category: "supplies",
    cas: "7732-18-5",
    formula: null,
    mw: null,
    sequence: null,
    size: "30 mL vial",
    purity: "USP grade",
    method: "Sterility and endotoxin tested",
    form: "Sterile liquid",
    storage: "Keep at room temperature. Do not freeze.",
    solubility: "Miscible, used as a diluent.",
    lot: "NR-2613-A",
    tagline: "Sterile bacteriostatic diluent, 0.9% benzyl alcohol.",
    description: "Sterile water containing 0.9% benzyl alcohol as a bacteriostatic agent. A standard laboratory diluent supplied as a sealed vial. No preparation or usage guidance is provided with this product.",
    apps: ["General laboratory diluent"],
    price: 13.05,
    box: 116,
    img: "nexus-vial"
  },
  {
    id: "sterile-vials",
    name: "Sterile Glass Vials, 10 mL",
    subtitle: "Type I borosilicate, pack of 25",
    category: "supplies",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "25 × 10 mL",
    purity: "Depyrogenated",
    method: "Sterility tested",
    form: "Empty glass vials",
    storage: "Keep at room temperature in the original packaging.",
    solubility: null,
    lot: "NR-2613-B",
    tagline: "Type I borosilicate vials with tamper-evident aluminium seals.",
    description: "Depyrogenated Type I borosilicate vials with butyl rubber stoppers and aluminium crimp seals. Empty laboratory glassware, supplied sterile.",
    apps: ["Laboratory sample storage", "Sterile sample handling"],
    price: 26,
    box: 231,
    img: "nexus-vial"
  },
  {
    id: "syringe-filters",
    name: "Syringe Filters, 0.22 µm",
    subtitle: "PES membrane, pack of 50",
    category: "supplies",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "50 × 33 mm",
    purity: "Sterile, individually wrapped",
    method: "Bubble-point tested",
    form: "Syringe filters",
    storage: "Keep at room temperature, dry.",
    solubility: null,
    lot: "NR-2613-C",
    tagline: "Sterilizing-grade filtration for aqueous solutions.",
    description: "Sterilizing-grade 0.22 µm polyethersulfone syringe filters with low protein binding and luer-lock fittings. Laboratory consumable, supplied sterile.",
    apps: ["Laboratory filtration", "Buffer clarification"],
    price: 34,
    box: 302,
    img: "nexus-vial"
  },
];


function getProductById(id) {
  return PRODUCTS.find(function (p) { return p.id === id; });
}
