/* Nexus Research: catalog of laboratory reagents and consumables.
   RESEARCH USE ONLY. Not for human or veterinary use.

   Every entry carries the identity and handling data a lab actually
   needs to work with the material: CAS, formula, molecular weight,
   purity and the method used to determine it, form, and storage.
   `lot` is the batch whose certificate of analysis is on file.
*/
const PRODUCTS = [
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    subtitle: "Copper tripeptide-1",
    category: "peptides",
    cas: "89030-95-5",
    formula: "C14H22CuN6O4",
    mw: "403.91 g/mol",
    sequence: "Gly-His-Lys · Cu(II)",
    size: "50 mg",
    purity: "≥98%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Lyophilized powder",
    storage: "Store at -20 °C, protected from light. Ships ambient as a lyophilized solid.",
    solubility: "Soluble in water and aqueous buffers.",
    lot: "NR-2601-A",
    tagline: "Copper-binding tripeptide used in extracellular matrix and fibroblast studies.",
    description: "GHK-Cu is the copper(II) complex of the tripeptide glycyl-L-histidyl-L-lysine, used in in-vitro investigation of collagen synthesis, fibroblast activity, and metalloprotein chemistry. Supplied as a lyophilized solid with identity confirmed by LC-MS and purity determined by HPLC-UV.",
    apps: ["Extracellular matrix studies", "Fibroblast culture models", "Metalloprotein chemistry"],
    price: 48.00,
    img: "nexus-vial"
  },
  {
    id: "ghk",
    name: "GHK Tripeptide",
    subtitle: "Glycyl-L-histidyl-L-lysine",
    category: "peptides",
    cas: "49557-75-7",
    formula: "C14H24N6O4",
    mw: "340.38 g/mol",
    sequence: "Gly-His-Lys",
    size: "50 mg",
    purity: "≥98%",
    method: "HPLC-UV, identity by LC-MS",
    form: "Lyophilized powder",
    storage: "Store at -20 °C, desiccated. Ships ambient as a lyophilized solid.",
    solubility: "Freely soluble in water.",
    lot: "NR-2601-B",
    tagline: "The uncomplexed tripeptide, for use as a reference or copper-free control.",
    description: "GHK is the free tripeptide corresponding to the copper complex GHK-Cu. It is commonly run as a copper-free control alongside GHK-Cu to separate peptide-driven effects from metal-driven effects in culture. Identity confirmed by LC-MS.",
    apps: ["Control for GHK-Cu experiments", "Peptide reference standard", "Chelation studies"],
    price: 39.00,
    img: "nexus-vial"
  },
  {
    id: "glutathione-reduced",
    name: "L-Glutathione, reduced",
    subtitle: "GSH",
    category: "biochemicals",
    cas: "70-18-8",
    formula: "C10H17N3O6S",
    mw: "307.32 g/mol",
    sequence: "γ-Glu-Cys-Gly",
    size: "1 g",
    purity: "≥98%",
    method: "HPLC-UV, titration",
    form: "Crystalline powder",
    storage: "Store at 2 to 8 °C, desiccated and protected from air. Oxidizes on exposure to moisture.",
    solubility: "Soluble in water, approx. 100 mg/mL.",
    lot: "NR-2601-C",
    tagline: "Reference thiol antioxidant for redox and oxidative stress assays.",
    description: "Reduced glutathione is the principal intracellular thiol antioxidant and a standard reagent in redox biology. Used to prepare standard curves for GSH/GSSG assays, as a reducing agent in buffers, and as a substrate in glutathione S-transferase work.",
    apps: ["GSH/GSSG ratio assays", "Redox buffer preparation", "Glutathione S-transferase substrate"],
    price: 34.00,
    img: "nexus-vial"
  },
  {
    id: "glutathione-oxidized",
    name: "L-Glutathione, oxidized",
    subtitle: "GSSG",
    category: "biochemicals",
    cas: "27025-41-8",
    formula: "C20H32N6O12S2",
    mw: "612.63 g/mol",
    sequence: "(γ-Glu-Cys-Gly)₂, disulfide-linked",
    size: "500 mg",
    purity: "≥98%",
    method: "HPLC-UV",
    form: "Crystalline powder",
    storage: "Store at 2 to 8 °C, desiccated.",
    solubility: "Soluble in water.",
    lot: "NR-2601-D",
    tagline: "The disulfide dimer, paired with GSH for redox ratio work.",
    description: "Oxidized glutathione is the disulfide-linked dimer of GSH. It is used as the oxidized reference in GSH/GSSG ratio determinations, in redox potential calibration, and as a substrate for glutathione reductase assays.",
    apps: ["GSH/GSSG standard curves", "Glutathione reductase assays", "Redox potential calibration"],
    price: 42.00,
    img: "nexus-vial"
  },
  {
    id: "nac",
    name: "N-Acetyl-L-cysteine",
    subtitle: "NAC",
    category: "biochemicals",
    cas: "616-91-1",
    formula: "C5H9NO3S",
    mw: "163.19 g/mol",
    sequence: "N-acetylated L-cysteine",
    size: "5 g",
    purity: "≥99%",
    method: "HPLC-UV, titration",
    form: "Crystalline powder",
    storage: "Store at room temperature, tightly sealed and desiccated.",
    solubility: "Freely soluble in water, approx. 200 mg/mL.",
    lot: "NR-2601-E",
    tagline: "Thiol reagent and cysteine precursor for cell culture work.",
    description: "N-Acetyl-L-cysteine is a cell-permeable thiol used in vitro as a reactive oxygen species scavenger, a cysteine source in culture media, and a mucolytic reagent in sample preparation. Supplied as a crystalline solid.",
    apps: ["ROS scavenging in culture", "Cysteine supplementation", "Sample liquefaction"],
    price: 28.00,
    img: "nexus-vial"
  },
  {
    id: "bacteriostatic-water",
    name: "Bacteriostatic Water",
    subtitle: "0.9% benzyl alcohol",
    category: "supplies",
    cas: "7732-18-5",
    formula: "H2O with 0.9% C7H8O",
    mw: "18.02 g/mol (water)",
    sequence: null,
    size: "30 mL vial",
    purity: "USP grade",
    method: "Sterility and endotoxin tested",
    form: "Sterile solution",
    storage: "Store at room temperature. Do not freeze.",
    solubility: "Miscible, used as a diluent.",
    lot: "NR-2601-F",
    tagline: "Multi-dose diluent for reconstituting lyophilized reagents.",
    description: "Sterile water containing 0.9% benzyl alcohol as a bacteriostatic agent, allowing a sealed vial to be entered multiple times during a work session. Standard laboratory diluent for reconstituting lyophilized powders.",
    apps: ["Reconstituting lyophilized reagents", "Multi-dose stock preparation", "General laboratory diluent"],
    price: 12.00,
    img: "nexus-vial"
  },
  {
    id: "sterile-vials",
    name: "Sterile Glass Vials, 10 mL",
    subtitle: "Type I borosilicate, pack of 25",
    category: "supplies",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "25 × 10 mL",
    purity: "Depyrogenated",
    method: "Sterility tested",
    form: "Sealed glass vials with butyl stoppers",
    storage: "Store at room temperature in original packaging.",
    solubility: null,
    lot: "NR-2601-G",
    tagline: "Type I borosilicate vials with tamper-evident aluminium seals.",
    description: "Depyrogenated Type I borosilicate vials with butyl rubber stoppers and aluminium crimp seals. Suitable for storing reconstituted stocks and aliquoting lyophilized material under sterile technique.",
    apps: ["Stock aliquoting", "Lyophilized storage", "Sterile sample handling"],
    price: 26.00,
    img: "nexus-vial"
  },
  {
    id: "syringe-filters",
    name: "Syringe Filters, 0.22 µm",
    subtitle: "PES membrane, pack of 50",
    category: "supplies",
    cas: null,
    formula: null,
    mw: null,
    sequence: null,
    size: "50 × 33 mm",
    purity: "Sterile, individually wrapped",
    method: "Bubble point tested",
    form: "Polyethersulfone membrane, luer-lock housing",
    storage: "Store at room temperature, dry.",
    solubility: null,
    lot: "NR-2601-H",
    tagline: "Sterilizing-grade filtration for aqueous solutions.",
    description: "Sterilizing-grade 0.22 µm polyethersulfone syringe filters with low protein binding and luer-lock fittings. Used to sterile-filter reconstituted aqueous stocks and buffers prior to use in culture.",
    apps: ["Sterile filtration of stocks", "Buffer clarification", "Culture media preparation"],
    price: 34.00,
    img: "nexus-vial"
  }
];

function getProductById(id) {
  return PRODUCTS.find(function (p) { return p.id === id; });
}
